version: "3.8"

services:
  php80:
    build:
      dockerfile: 8.0/Dockerfile
      context: .docker/php
    container_name: fcc_php80
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  php81:
    build:
      dockerfile: 8.1/Dockerfile
      context: .docker/php
    container_name: fcc_php81
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

  php82:
    build:
      dockerfile: 8.2/Dockerfile
      context: .docker/php
    container_name: fcc_php82
    restart: "no"
    networks:
      - fcc_network
    volumes:
      - ./:/repo

networks:
  fcc_network: